### ISSUE TITLE
make async configurable

### ISSUE THREAD

**Issue by ikkez** [xfra35/f3-cron#10]
can you make async and option like the rest? 
I have a client server that has a poorly setup php cli and i need to fallback to some traditional job handling via web call that doesnt use the binary under the hood.

**Comment by xfra35** [comment]
Hey @ikkez. Sorry for the delay.
Just force the binary to `NULL` and you're all set:

```php
$cron=Cron::instance();
$cron->binary(NULL,TRUE); // no binary = no asynchronicity
```
