### ISSUE TITLE
[Hint] `max_execution_time` and Cronjobs

### ISSUE THREAD

**Issue by exodus4d** [xfra35/f3-cron#7]
I run into a problem where multiple PHP processes for the same cronJob were active. 
If you have a job that is executed very frequently (e.g. every minute), the next trigger starts a new  PHP process in case the **previous job is not finished** already :)

This can happen for long running tasks, or a DB connection that could not established and no "timeout" was set.....

 I figured out, that _PHP CLI_ scripts are not affected by `max_execution_time` set in your `php.ini` config file. 
> "The default setting is 30. When running PHP from the command line the default setting is 0."
source: http://php.net/manual/en/info.configuration.php#ini.max-execution-time

So even if a `max_execution_time` is set, it is ignored. In case there is no `timeout` set for e.g. a DB connection, the PHP script runs forever...
![41500026-b7aec26e-718a-11e8-93bb-ebbeb907389c](https://user-images.githubusercontent.com/9299033/41508232-9c557280-7241-11e8-94e4-624b211c02e5.png)

So adding something like this, can help:
```
ini_set('max_execution_time', 300)
```

**Comment by ikkez** [comment]
Good addition for the docs, but I think it should not go into the plugin itself (or be configurable) as the use cases might differ here and there.. i.e. I have cases where the cron job run for 20min or longer. 

@xfra35 would you mind tagging a new release with the latest commit? ..I'm currently using `"xfra35/f3-cron": "dev-master#eba0a5574a8c35623307dd27135a67d76e4da12e as 1.2",` in composer, which works but i dont like it 😅

**Comment by xfra35** [comment]
Hi guys, sorry for the delay.

@exodus4d thanks for the report. I'm wondering how the plugin should handle this.

I'm thinking about 4 solutions:

1. mention that issue in the docs and let developpers handle it
2. set automatically `max_execution_time` inside the `execute()` method (although guessing the right value out of a crontab schedule seems quite tricky)
3. add a new optional parameter to the `set()` method, allowing to define a max execution time for each job. E.g: `$cron->set('Job1', 'App->job1', '* * * * *', 59)`
4. add a new optional parameter to the `set()` method, allowing to prevent parallel calls. E.g: `$cron->set('Job1', 'App->job1', '* * * * *', FALSE)` (which would internally trigger a call to the framework `mutex()` method)

What's your opinion about it?

@ikkez `v1.2.1` has been released

**Comment by xfra35** [comment]
Actually, I had already updated the docs long time ago, but forgot to push 😅

See https://github.com/xfra35/f3-cron#overlapping-jobs
