### ISSUE TITLE
Issue with the ini file in the documentation

### ISSUE THREAD

**Issue by fatfreelogin** [xfra35/f3-cron#8]
Jsut wanted to let you know that there is an issue with the ini file setup that is mentioned in the documentation: 

The line 
`script = cron.php`
seems to break the cronjob, if the line is omitted, everything seems to be working as it should.
I assume that the script-line loads the cron library? It is already autoloaded since it sits in the lib folder (if you follow the same documentation).

**Comment by xfra35** [comment]
By default, `script = index.php`. See https://github.com/xfra35/f3-cron#script-path

The line you're referencing is just a random example of INI configuration.

I have replaced it with `script = /path/to/index.php` to avoid confusion.
